# probe_only: true
probes:
  - service: Home
    role: server
    http:
      url: "https://{{ .Host.Name }}"
      headers:
      no_check_certificate: true
    command:
      command: "mackerel-plugin-memcached -host 10.8.0.1"
      graph_defs: on
  - service: Home
    role: server
    command:
      command: "mackerel-plugin-nginx -host 10.8.0.1 -port 80"
      graph_defs: on

  - service: Home
    ping:
      address: '{{ or .Host.IPAddresses.en0 .Host.IPAddresses.eth0 }}'
      count: 3
      timeout: "500ms"
