name: Release
on:
  push:
    branches:
      - "!**/*"
    tags:
      - "v*"

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.15

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: setup tools
        run: |
          mkdir ~/bin
          curl -sL https://github.com/Songmu/goxz/releases/download/v0.4.1/goxz_v0.4.1_linux_amd64.tar.gz | tar zxvf - && install goxz_v0.4.1_linux_amd64/goxz ~/bin/
          curl -sL https://github.com/tcnksm/ghr/releases/download/v0.13.0/ghr_v0.13.0_linux_amd64.tar.gz | tar zxvf - && install ghr_v0.13.0_linux_amd64/ghr ~/bin/

      - name: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          export PATH=~/go/bin:~/bin:$PATH
          make setup_ci
          make dist
          make release

      - name: docker
        run: |
          export TAG=$(echo $GITHUB_REF | cut -d/ -f3)
          echo $DOCKER_TOKEN | docker login -u fujiwara --password-stdin
          for dir in docker/*
          do
            echo "Building $dir"
            name=$(basename $dir)
            docker build --build-arg version=$TAG \
              -t fujiwara/maprobe:${TAG}-${name} \
              -f ${dir}/Dockerfile \
              .
            docker push fujiwara/maprobe:${TAG}-${name}
          done
        env:
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
